name: marvel_characters
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  crypto: ^3.0.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_launcher_icons: ^0.11.0
  http: ^0.13.5
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/icon.png'
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/
